plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sockc.unicomhook'
    compileSdk 34

    def signingKeystorePath = System.getenv("SIGNING_KEYSTORE_PATH")
    def signingStorePassword = System.getenv("KEYSTORE_PASSWORD")
    def signingKeyAlias = System.getenv("KEY_ALIAS")
    def signingKeyPassword = System.getenv("KEY_PASSWORD")
    def hasReleaseSigning = signingKeystorePath && signingStorePassword && signingKeyAlias && signingKeyPassword

    signingConfigs {
        if (hasReleaseSigning) {
            release {
                storeFile file(signingKeystorePath)
                storePassword signingStorePassword
                keyAlias signingKeyAlias
                keyPassword signingKeyPassword
            }
        }
    }

    defaultConfig {
        applicationId "com.sockc.unicomhook"
        minSdk 24
        targetSdk 34
        versionCode 120
        versionName "1.2.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    compileOnly 'de.robv.android.xposed:api:82'
}
