plugins {
    id 'com.android.application'
}

android {
    namespace 'com.sockc.unicomhook'
    compileSdk 36

    def signingKeystorePath = System.getenv("SIGNING_KEYSTORE_PATH")
    def signingStorePassword = System.getenv("KEYSTORE_PASSWORD")
    def signingKeyAlias = System.getenv("KEY_ALIAS")
    def signingKeyPassword = System.getenv("KEY_PASSWORD")
    def hasReleaseSigning = signingKeystorePath && signingStorePassword && signingKeyAlias && signingKeyPassword

    signingConfigs {
        if (hasReleaseSigning) {
            release {
                storeFile file(signingKeystorePath)
                storePassword signingStorePassword
                keyAlias signingKeyAlias
                keyPassword signingKeyPassword
            }
        }
    }

    defaultConfig {
        applicationId "com.sockc.unicomhook"
        minSdk 26
        targetSdk 34
        versionCode 1433
        versionName "1.4.3.3"
    }

    buildTypes {
        debug {
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }
        release {
            minifyEnabled false
            if (hasReleaseSigning) {
                signingConfig signingConfigs.release
            }
        }
    }
}

dependencies {
    compileOnly 'io.github.libxposed:api:101.0.1'
    implementation 'io.github.libxposed:interface:101.0.0'
    implementation 'io.github.libxposed:service:101.0.0'
}
